name: 'Beeload to Swarm network'
description: 'Toolkit to uploading data to Swarm network with GitHub Actions'
branding:
  icon: upload-cloud
  color: orange
inputs:
  bee-url:
    description: 'URL of Bee node'
    required: false
    default: 'https://bee-9.gateway.ethswarm.org'
  bzz-link-url:
    description: 'URL of for Bzz.link'
    required: false
    default: 'https://<<CID>>.bzz.link'
  postage-batch-id:
    description: 'Batch ID of Postage Stamp that will be used for upload'
    required: false
    default: '0000000000000000000000000000000000000000000000000000000000000000'
  dir:
    description: 'Path to build directory that should be uploaded. Default: ./build'
    required: false
    default: './build'
  preview:
    description: 'Specifies if PR preview comment should be created for PR branches. Default: false'
    required: false
    default: 'false'
  token:
    description: 'Token to be used for creating the PR comment. Default: GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
  extra-params:
    description: 'Extra parameters passed to Swarm CLI calls'
    required: false
outputs:
  swarm-hash:
    description: 'Swarm hash of the uploaded content'
    value: ${{ steps.upload.outputs.swarm-hash }}
  url:
    description: 'Bzz link URL'
    value: ${{ steps.upload.outputs.bzz-link }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - run: cd ${{ github.action_path }} && npm ci
      shell: bash

    - id: upload
      name: Upload to Swarm
      shell: bash
      run: |
        HASH=$(${{ github.action_path }}/node_modules/.bin/swarm-cli upload ${{ inputs.dir }} --bee-api-url ${{ inputs.bee-url }} --quiet --stamp ${{ inputs.postage-batch-id }} ${{ inputs.extra-params }})
        CID=$(${{ github.action_path }}/convert-to-cid.js $HASH)
        BZZ_LINK_BASE_URL="${{ inputs.bzz-link-url }}"
        BZZ_LINK_URL=${BZZ_LINK_BASE_URL/<<CID>>/$CID}
        echo "::set-output name=swarm-hash::$HASH"
        echo "::set-output name=bzz-link::$BZZ_LINK_URL"
        echo "::set-output name=git-hash::$(git log -1 --skip=1  --pretty=%H | tr -d '\n')"
        echo "::set-output name=git-message::$(git log -1 --skip=1  --pretty=%B | tr -d '\n')"
        echo "Swarm Hash: $HASH"
        echo "Bzz link URL: $BZZ_LINK_URL"

    - name: Find preview comment
      if: inputs.preview == 'true' && github.event.pull_request.number
      uses: peter-evans/find-comment@v1
      id: comment
      with:
        token: ${{ inputs.token }}
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: PR preview in Swarm

    - name: Create or update preview comment
      if: inputs.preview == 'true' && github.event.pull_request.number
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ inputs.token }}
        comment-id: ${{ steps.comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ## 🐝 PR preview in Swarm

          **Preview URL:** ${{ steps.upload.outputs.bzz-link }}
          **Swarm Hash:** `${{ steps.upload.outputs.swarm-hash }}`
          **Commit Hash:** ${{ steps.upload.outputs.git-hash }}
          **Commit Message:** ${{ steps.upload.outputs.git-message }}
        edit-mode: replace
