name: Check

on:
  push:
    branches:
      - 'master'
#  pull_request:
#    branches:
#      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update supported Bee action
        uses: ethersphere/update-supported-bee-action@v1
#        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
